[project]
name = "nlp-project"
version = "0.1.0"
description = "NLP project environment"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pandas",
    "jupyter",
    "ipywidgets",
    "ipykernel",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "torch",
    "torchvision",
    "torchaudio",
    "openai",
    "nltk",
    "datasets",
    "ollama-python",
    "gradient",
]

[tool.uv]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'"
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu" },
]
torchvision = [
  { index = "pytorch-cpu" },
]
